version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./src:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      container_name:
        cangmishu-php-fpm
      build:
        context: ./php
      volumes:
        - ../src:/var/www/html
      expose:
        - "9000"
      depends_on:
        - mysql
        - redis

### PHP-CLI Container #######################################

    php-cli:
      container_name:
        cangmishu-php-cli
      build:
        context: ./php_cli
      volumes:
        - ../src:/var/www/html
      depends_on:
        - mysql
        - redis
      tty: true

### Nginx Server Container ##################################

    nginx:
      container_name:
        cangmishu-nginx
      build:
        context: ./nginx
      volumes:
          - ../src:/var/www/html
          - ../static:/var/www/static
      ports:
          - "${NGINX_HTTP_PORT}:80"
          - "${NGINX_HTTPS_PORT}:443"
      depends_on:
          - php-fpm


### Redis Container #########################################

    redis:
      container_name:
        cangmishu-redis
      image: redis:3.2.11
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./data/redis:/data

### Volumes Setup ###########################################

volumes:
  mysql-data:
networks:
  default:
    external:
      name: ${USER_NETWORK}
